version: '3'
services:
  runner:
    image: mediauncovered/explorer-server:dev
    build: .
    environment:
        MODEL_PATH: './models/model'
    ports:
      - 5000:5000
    volumes:
      - ./models:/flask-explorer/models
